apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "todo-chat.fullname" . }}-frontend
  labels:
    {{- include "todo-chat.labels" . | nindent 4 }}
    component: frontend
spec:
  replicas: {{ .Values.app.frontend.replicas }}
  selector:
    matchLabels:
      {{- include "todo-chat.selectorLabels" . | nindent 6 }}
      component: frontend
  template:
    metadata:
      annotations:
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "todo-chat.labels" . | nindent 8 }}
        component: frontend
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "todo-chat.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: frontend
          {{- with .Values.app.frontend.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.app.frontend.image.repository }}:{{ .Values.app.frontend.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.app.frontend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.app.frontend.service.port }}
              protocol: TCP
          env:
            - name: NEXT_PUBLIC_API_BASE_URL
              value: "/api"
          {{- with .Values.app.frontend.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.app.frontend.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.app.frontend.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.app.frontend.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
